#!usr/bin/python

""" ** Change Return Program ** -
The user enters the cost and then the amount of money given.
The program will figure out how much change is due and the number of 
quarters, nickels, dimes and pennies to give back."""



